name: Project Status → Discord

on:
  schedule:
    - cron: "*/5 * * * *"   # recomendado: cada 5 min
  workflow_dispatch: {}

permissions:
  contents: write  # para commitear el archivo de estado

env:
  PROJECT_OWNER_TYPE: user
  PROJECT_OWNER: MarbiFox
  PROJECT_NUMBER: "1"
  STATE_FILE: ".github/project-status-cache.json"

jobs:
  watch-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Leer Project y detectar cambios de Status
        id: watch
        uses: actions/github-script@v8
        with:
          github-token: ${{ secrets.PROJECT_PAT }}
          script: |
            const fs = require('fs');
            const path = require('path');

            const ownerType = process.env.PROJECT_OWNER_TYPE; // "user"
            const owner = process.env.PROJECT_OWNER;          // "MarbiFox"
            const number = parseInt(process.env.PROJECT_NUMBER, 10); // 1
            const stateFile = process.env.STATE_FILE;

            const query = `query($owner: String!, $number: Int!, $cursor: String){
              user(login:$owner){
                projectV2(number:$number){
                  id title
                  items(first:100, after:$cursor){
                    nodes{
                      id
                      content{
                        __typename
                        ... on Issue { number title url }
                        ... on PullRequest { number title url }
                      }
                      fieldValues(first:50){
                        nodes{
                          ... on ProjectV2ItemFieldSingleSelectValue {
                            name
                            field { ... on ProjectV2SingleSelectField { name } }
                          }
                        }
                      }
                    }
                    pageInfo{ hasNextPage endCursor }
                  }
                }
              }
            }`;

            async function fetchAll(){
              let items = [];
              let cursor = null;
              while (true) {
                const res = await github.graphql(query, { owner, number, cursor });
                const proj = res.user?.projectV2;
                if (!proj) {
                  core.setFailed(`No se encontró el Project user=${owner} #${number}`);
                  return [];
                }
                items.push(...proj.items.nodes);
                if (!proj.items.pageInfo.hasNextPage) break;
                cursor = proj.items.pageInfo.endCursor;
              }
              return items;
            }

            // Cargar estado previo desde el repo (si existe el archivo)
            let prev = {};
            try { prev = JSON.parse(fs.readFileSync(stateFile, 'utf8')); } catch {}

            const items = await fetchAll();
            const current = {};
            const changes = [];

            const getStatus = (it) => {
              const n = it.fieldValues.nodes.find(n => n?.field?.name === 'Status');
              return n?.name || null;
            };

            for (const it of items) {
              const status = getStatus(it);
              const title = it.content?.title || '(sin título)';
              const url   = it.content?.url || null;
              const type  = it.content?.__typename || 'Item';
              current[it.id] = { status, title, url, type };

              const before = prev[it.id]?.status ?? null;
              if (before !== null && before !== status) {
                changes.push({ title, url, type, from: before, to: status });
              }
            }

            // Guardar estado actual para la próxima corrida
            fs.mkdirSync(path.dirname(stateFile), { recursive: true });
            fs.writeFileSync(stateFile, JSON.stringify(current, null, 2));

            // Outputs
            core.setOutput('has_changes', String(changes.length > 0));
            const msg = changes.length
              ? '📢 **¡Cambios de Status en el Project #' + number + '!**\n\n'
                + changes.map(c => `• **${c.type}** [${c.title}](${c.url}) — \`${c.from}\` ➜ \`${c.to}\``).join('\n')
              : '';
            core.setOutput('message', msg);
            core.setOutput('count', String(changes.length));

      - name: Persistir estado al repo
        if: always()
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "chore(project-watcher): actualizar caché de Status"
          file_pattern: ${{ env.STATE_FILE }}

      - name: Notificar en Discord (ID + Token)
        if: steps.watch.outputs.has_changes == 'true'
        uses: appleboy/discord-action@v1.2.0
        with:
          webhook_id: ${{ secrets.DISCORD_UPDATES_ID }}
          webhook_token: ${{ secrets.DISCORD_UPDATES_TOKEN }}
          username: "GitHub Updates"
          avatar_url: "https://cdn.pixabay.com/photo/2022/01/30/13/33/github-6980894_640.png"
          message: ${{ steps.watch.outputs.message }}
